"""empty message

Revision ID: eb78ab4329ff
Revises: 
Create Date: 2019-03-10 03:59:41.838966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb78ab4329ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('hash_item', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('price_item', sa.Integer(), nullable=True),
    sa.Column('file_item', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('hash_item')
    )
    op.create_index(op.f('ix_items_file_name'), 'items', ['file_name'], unique=False)
    op.create_index(op.f('ix_items_hash_item'), 'items', ['hash_item'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_hash_item'), table_name='items')
    op.drop_index(op.f('ix_items_file_name'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
